### ISSUE TITLE
Reader unresponsive after sleeping and waking device

### ISSUE THREAD

**Issue by brblakley** [CardFlight/cardflight-ios#41]
Steps to reproduce (using CardFlight iOS SDK 3.1 with iOS 9.3.1):

- Call `[[CFTSessionManager sharedInstance] setLogging:YES]`.
- Call `-[CFTSessionManager setApiToken:accountToken:]` with an EMV-compatible account’s tokens.
- Wait until the console reports “is EMV ready:Yes”.
- Connect an EMV-compatible reader.
- In `-[CFTReaderDelegate readerIsConnected:withError:]`, call `-[CFTReader beginEMVTransactionWithAmount:andChargeDictionary:]` and `-[CFTReader swipeHasTimeout:NO]`.
- Press the device’s On/Off Sleep/Wake button.
- The screen will turn off, then a few seconds later it automatically turns back on showing the lock screen, and finally automatically will turn back off. Wait until that sequence has finished.
- Unlock the device.
- Insert a card in the reader.

Expected result: The transaction to progress, e.g. `-[CFTReaderDelegate emvMessage:]` to be called with `EMVMessage_PLEASE_WAIT` and so on.

Actual result: The transaction does not progress. I.e. no `CFTReaderDelegate` methods are called.

Log:
```
2016-04-01 09:33:33.607 CardFlight -[CFTSessionManager setApiToken:accountToken:] Version 3.1
2016-04-01 09:33:33.607 CardFlight -[CFTSessionManager setApiToken:accountToken:] API Key:REDACTED Account Token:REDACTED
2016-04-01 09:33:33.607 CardFlight -[CFTAPIResource processRequestWithMethod:toEndpoint:withParameters:success:failure:] URL - https://api.getcardflight.com/merchant_account/REDACTED/info?key=REDACTED
2016-04-01 09:33:34.445 CardFlight __85-[CFTAPIResource processRequestWithMethod:toEndpoint:withParameters:success:failure:]_block_invoke Code - 200
2016-04-01 09:33:34.448 CardFlight __46-[CFTSessionManager setApiToken:accountToken:]_block_invoke is EMV ready:Yes
2016-04-01 09:33:39.603 CardFlight -[CFTReader readerAttached] Call to readerIsAttached UNHANDLED
2016-04-01 09:33:39.609 CardFlight -[CFTReader walkerConnected:] Walker Detected
2016-04-01 09:33:39.609 MyReaderDelegate readerIsConnected:YES withError:(null)
2016-04-01 09:33:39.618 CardFlight beingEMVTransactionWithAmount:0.5
2016-04-01 09:33:39.624 MyReaderDelegate emvMessage:13 (Dip or swipe card)
2016-04-01 09:33:39.625 CardFlight swipeHasTimeout:No
2016-04-01 09:33:39.625 CardFlight -[CFTReader walkerConnected:] Call to readerIsConnected:YES withError:nil
```

**Comment by hokiewalrus** [comment]
Fixed in version 3.2

**Comment by brblakley** [comment]
@hokiewalrus Thanks for looking into this. Unfortunately, I’ll still seeing this issue with 3.2 and the above steps (replacing `setApiToken:accountToken:` with `setApiToken:accountToken:completed:`). That is, after going through the above steps, the only way I can get a response from the reader is by disconnecting the reader (which does trigger the expected callbacks `readerIsDisconnected`) and then re-connecting it.

**Comment by hokiewalrus** [comment]
We will look into this

**Comment by patmisch** [comment]
@brblakley Were you able to figure anything out with this?

**Comment by brblakley** [comment]
@patmisch, no, I don’t think I did. Although, I’m no longer working on the app that was using CardFlight so I’m not sure if a more recent CF SDK update changed any of this.
